### PR TITLE
Feedback integration

### PR DESCRIPTION
**Pull request by BastijnKostense**

### CODE REVIEW

**Comment by mikebeijen** [comment]
This PR implements several improvements with regard to the feedback our supervisor gave us:
* Turned agree into using7 point Likert scale 
* Changed clarity question into binary yes/no, textbox pops for explaination pops up if no is ticked
* Introduction is improved: explains the questions, states that sounds en video should be working, adds pay.
* improved assessment interface: values for radio buttons are now shown underneath it.

Proof!:

Improved introduction:
image

Improved assessment interface:
image

**Comment by mikebeijen** [comment]
Todo: 
* reward = $0,10 per video +$0.01 per 10 sec video
* edit training videos
* wait until video completed before submitting task?

**Comment by BastijnKostense** [comment]
Will do the feedback! As for the "wait until videos completed", I tried it but all the controls of the video showed up again so that didn't work. I might try something hacky like turning on autoplay and giving the button a timeout of the same amount as the video length.

**Comment by BastijnKostense** [comment]
Doneee

**Pull request merged**
